// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_market
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2022-08-23, STEPS: `[20, ]`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/debug/node-template
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_market
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./pallets/market/src/weights2.rs
// --template
// ./.maintain/frame-weight-template.hbs


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_market.
pub trait WeightInfo {
	fn bond() -> Weight;
	fn withdraw() -> Weight;
	fn payout_gateway_nodes() -> Weight;
	fn payout_provider_nodes() -> Weight;
	fn payout_client_nodes() -> Weight;
}

/// Weights for pallet_market using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn bond() -> Weight {
		(1_935_063_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn withdraw() -> Weight {
		(992_291_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn payout_gateway_nodes() -> Weight {
		(649_652_560_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2002 as Weight))
			.saturating_add(T::DbWeight::get().writes(2001 as Weight))
	}
	fn payout_provider_nodes() -> Weight {
		(647_246_477_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2002 as Weight))
			.saturating_add(T::DbWeight::get().writes(2001 as Weight))
	}
	fn payout_client_nodes() -> Weight {
		(655_112_903_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2002 as Weight))
			.saturating_add(T::DbWeight::get().writes(2001 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn bond() -> Weight {
		(1_935_063_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	fn withdraw() -> Weight {
		(992_291_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	fn payout_gateway_nodes() -> Weight {
		(649_652_560_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2002 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2001 as Weight))
	}
	fn payout_provider_nodes() -> Weight {
		(647_246_477_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2002 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2001 as Weight))
	}
	fn payout_client_nodes() -> Weight {
		(655_112_903_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2002 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2001 as Weight))
	}
}
