// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_market
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-09-09, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `gzhlinux`, CPU: `AMD Ryzen 7 5800H with Radeon Graphics`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/substrate
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_market
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./frame/market/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_market.
pub trait WeightInfo {
	fn bond() -> Weight;
	fn withdraw() -> Weight;
	fn payout_gateway_nodes() -> Weight;
	fn payout_provider_nodes() -> Weight;
	fn payout_client_nodes() -> Weight;
}

/// Weights for pallet_market using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: System Account (r:2 w:2)
	// Storage: Market Staking (r:1 w:1)
	fn bond() -> Weight {
		(39_599_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
	// Storage: Market Staking (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	fn withdraw() -> Weight {
		(38_551_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
	// Storage: Market GatewayReward (r:1001 w:1000)
	// Storage: System Account (r:1001 w:1001)
	fn payout_gateway_nodes() -> Weight {
		(19_653_948_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2002 as u64))
			.saturating_add(T::DbWeight::get().writes(2001 as u64))
	}
	// Storage: Market ProviderReward (r:1001 w:1000)
	// Storage: System Account (r:1001 w:1001)
	fn payout_provider_nodes() -> Weight {
		(20_235_011_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2002 as u64))
			.saturating_add(T::DbWeight::get().writes(2001 as u64))
	}
	// Storage: Market ClientReward (r:1001 w:0)
	// Storage: System Account (r:1001 w:1001)
	// Storage: Market GatewayReward (r:0 w:1000)
	fn payout_client_nodes() -> Weight {
		(20_273_283_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2002 as u64))
			.saturating_add(T::DbWeight::get().writes(2001 as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: System Account (r:2 w:2)
	// Storage: Market Staking (r:1 w:1)
	fn bond() -> Weight {
		(39_599_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as u64))
			.saturating_add(RocksDbWeight::get().writes(3 as u64))
	}
	// Storage: Market Staking (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	fn withdraw() -> Weight {
		(38_551_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as u64))
			.saturating_add(RocksDbWeight::get().writes(3 as u64))
	}
	// Storage: Market GatewayReward (r:1001 w:1000)
	// Storage: System Account (r:1001 w:1001)
	fn payout_gateway_nodes() -> Weight {
		(19_653_948_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2002 as u64))
			.saturating_add(RocksDbWeight::get().writes(2001 as u64))
	}
	// Storage: Market ProviderReward (r:1001 w:1000)
	// Storage: System Account (r:1001 w:1001)
	fn payout_provider_nodes() -> Weight {
		(20_235_011_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2002 as u64))
			.saturating_add(RocksDbWeight::get().writes(2001 as u64))
	}
	// Storage: Market ClientReward (r:1001 w:0)
	// Storage: System Account (r:1001 w:1001)
	// Storage: Market GatewayReward (r:0 w:1000)
	fn payout_client_nodes() -> Weight {
		(20_273_283_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2002 as u64))
			.saturating_add(RocksDbWeight::get().writes(2001 as u64))
	}
}
