// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_gateway
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-09-09, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `gzhlinux`, CPU: `AMD Ryzen 7 5800H with Radeon Graphics`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/substrate
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_gateway
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./frame/gateway/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_gateway.
pub trait WeightInfo {
	fn register_gateway_node() -> Weight;
	fn heartbeat() -> Weight;
	fn offline() -> Weight;
}

/// Weights for pallet_gateway using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Gateway GatewayNodeCount (r:1 w:1)
	// Storage: Gateway GatewayNodes (r:1 w:1)
	// Storage: Market Staking (r:1 w:1)
	// Storage: Market GatewayBaseFee (r:1 w:0)
	// Storage: Market TotalStaked (r:1 w:1)
	// Storage: Gateway Gateways (r:1 w:1)
	// Storage: Gateway AccountPeerMap (r:1 w:1)
	// Storage: Gateway GatewayNodeRegisterTime (r:0 w:1)
	fn register_gateway_node() -> Weight {
		Weight::from_ref_time(39_592_000 as u64)
			.saturating_add(T::DbWeight::get().reads(7 as u64))
			.saturating_add(T::DbWeight::get().writes(7 as u64))
	}
	// Storage: Gateway GatewayNodes (r:1 w:1)
	fn heartbeat() -> Weight {
		Weight::from_ref_time(22_415_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: Gateway GatewayNodes (r:1 w:1)
	// Storage: Gateway GatewayNodeCount (r:1 w:1)
	// Storage: Gateway Gateways (r:1 w:1)
	// Storage: Gateway AccountPeerMap (r:1 w:1)
	// Storage: Gateway GatewayNodeRegisterTime (r:1 w:1)
	// Storage: Gateway TotalOnlineTime (r:1 w:1)
	// Storage: Market GatewayBaseFee (r:1 w:0)
	// Storage: Market Staking (r:1 w:1)
	// Storage: Market TotalStaked (r:1 w:1)
	fn offline() -> Weight {
		Weight::from_ref_time(35_333_000 as u64)
			.saturating_add(T::DbWeight::get().reads(9 as u64))
			.saturating_add(T::DbWeight::get().writes(8 as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Gateway GatewayNodeCount (r:1 w:1)
	// Storage: Gateway GatewayNodes (r:1 w:1)
	// Storage: Market Staking (r:1 w:1)
	// Storage: Market GatewayBaseFee (r:1 w:0)
	// Storage: Market TotalStaked (r:1 w:1)
	// Storage: Gateway Gateways (r:1 w:1)
	// Storage: Gateway AccountPeerMap (r:1 w:1)
	// Storage: Gateway GatewayNodeRegisterTime (r:0 w:1)
	fn register_gateway_node() -> Weight {
		Weight::from_ref_time(39_592_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(7 as u64))
			.saturating_add(RocksDbWeight::get().writes(7 as u64))
	}
	// Storage: Gateway GatewayNodes (r:1 w:1)
	fn heartbeat() -> Weight {
		Weight::from_ref_time(22_415_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: Gateway GatewayNodes (r:1 w:1)
	// Storage: Gateway GatewayNodeCount (r:1 w:1)
	// Storage: Gateway Gateways (r:1 w:1)
	// Storage: Gateway AccountPeerMap (r:1 w:1)
	// Storage: Gateway GatewayNodeRegisterTime (r:1 w:1)
	// Storage: Gateway TotalOnlineTime (r:1 w:1)
	// Storage: Market GatewayBaseFee (r:1 w:0)
	// Storage: Market Staking (r:1 w:1)
	// Storage: Market TotalStaked (r:1 w:1)
	fn offline() -> Weight {
		Weight::from_ref_time(35_333_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(9 as u64))
			.saturating_add(RocksDbWeight::get().writes(8 as u64))
	}
}
